### ISSUE TITLE
ValueError: Inconsistent number of specified drift terms supplied.

### ISSUE THREAD

**Issue by giswangsj** [GeoStat-Framework/PyKrige#105]
when I run the example Three-Dimensional Kriging Example
I get the following error:
File "Three-DimensionalKrigingExample.py", line 35, in <module>
    k3d, ss3d = uk3d.execute('grid', gridx, gridy, gridz, specified_drift_arrays=[xg, yg, zg])
  File "C:\Python\Python36\lib\site-packages\pykrige\uk3d.py", line 858, in execute
    raise ValueError("Inconsistent number of specified "
ValueError: Inconsistent number of specified drift terms supplied.

**Comment by rth** [comment]
Thanks for the report. I can confirm. This is a reason we should IMO move (or copy) at least some of the example from the readme to examples/ so that they would be run when building docs and we can detect such issues.

I'm not quite sure what the `specified_drift_arrays` should be in this case, @bsmurphy would probably know..

**Comment by MuellerSeb** [comment]
This file no longer exists. Closing.
