### ISSUE TITLE
Different distances apart from the euclidean

### ISSUE THREAD

**Issue by gsantam** [GeoStat-Framework/PyKrige#120]
Hi,

have you considered adding other distances apart from the euclidean, or letting the user customize their own distance? If you are interested in this feature I could start working on it.

**Comment by rth** [comment]
Currently, we also support great-circle distance.

I think other distance metrics could be interesting but some code re-factoring (https://github.com/bsmurphy/PyKrige/issues/56 and https://github.com/bsmurphy/PyKrige/issues/31) might be beneficial before doing that. Currently, as we saw with the great-circle distance adding a new distance requires repetitive changes all through the code base (also related to https://github.com/bsmurphy/PyKrige/issues/121), and it would be preferable if that could be avoided as much as possile.

You are very welcome to contribute in general though.

**Comment by MuellerSeb** [comment]
One thing to have in mind: As with the great-circle distance, the meaning of anisotropy depends on your metric. When handling #133 with an isotropic n-dimensional kriging, the distance calculation could be just a plugin.

Since [scipys ``cdist``](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) is used to calculate pairwise distances, we could simply provide all their metrics by passing through the ``metric`` keyword.

**Comment by MuellerSeb** [comment]
We will discuss this here: #143. Closing for now. Feel free to Re-open or (better) discuss in the linked issue.
