### ISSUE TITLE
Unrealistic output

### ISSUE THREAD

**Issue by srimaljq1** [GeoStat-Framework/PyKrige#141]
Hi 
Nice library. I'm fairly new to kriging have simple dataset of 50 points, where the **data values are non-negative** but ordinary krigging gives me a lot of **negative predictions** on the same grid as the original data.

So for e.g:
 OK = OrdinaryKriging(d.x, d.y, d.v, verbose=True, variogram_model='linear',enable_plotting=True)
 z, ss = OK.execute('grid',d.x, d.y) 

z gives has values such as [ 1.67574979, -4.30622435, -4.30622435, ...

The only tuneable parameter seems to be variogram_model and this happens with all of its values(linear, gaussian.. etc)

Is this as expected?

Is there any metric which I can use from pykrige which will tell me how much I should trust my kriging model before using it?

Thanks

Does

**Comment by MuellerSeb** [comment]
Could you provide data and a script to reproduce the problem?

**Comment by srimaljq1** [comment]
Hi

Here is a colab notebook which reproduces the problem (with the data):

https://colab.research.google.com/drive/1vbVhLfHt-C-_R84bxuKMMyuskegTpUMa

Based on my understanding (which may not be correct) here are the original and predictions for the same data points which show negative predictions

![image](https://user-images.githubusercontent.com/62587687/77487794-19bdea00-6e7f-11ea-88a3-2e6749a31009.png)

I'm not sure if that notebook lets you download the data so here's a separate link to the data you could download:

https://drive.google.com/open?id=1cNj_tPcSy7qrZ5NA8dsDpvO3TLUpmhoj


Thanks

**Comment by srimaljq1** [comment]
I'm not sure if that notebook lets you download the data so here's a separate link to the data you could download:

https://drive.google.com/open?id=1cNj_tPcSy7qrZ5NA8dsDpvO3TLUpmhoj

**Comment by antunesleo** [comment]
Shouldn't the grid size in the execute method be different (bigger) than the initialization grid?

**Comment by srimaljq1** [comment]
Hi

First of all, let me warn you that I'm fairly new to kriging :-)

My intention here was to see what value the interpolation would give on the original data used to build the model, which is why I passed on x and y values..


Could you please explain or point to something which explains why 
> Shouldn't the grid size in the execute method be different (bigger) than the initialization grid?

Thanks

**Comment by MuellerSeb** [comment]
> Shouldn't the grid size in the execute method be different (bigger) than the initialization grid?

It doesn't need to, but it should reproduce the data.

## Making an educated guess
Your data is not suitable to fit a variogram, since you result in a really high nugget and a fairly low slope in the estimated variogram. This again means, that your kriging matrix is almost singular, which results in numerical errors during the execution of ordinary kriging. And that eventually results in the erroneous output.

I can't tell from your plots, if your data shows spatial correlation, since you only plotted x-v and y-v. Could you try making a 3D scatter plot?

## Hint
Since you are new to kriging, I could at least recommend you the [wikipedia article for regression kriging](https://en.wikipedia.org/wiki/Regression-kriging).
There, a nice decision tree is shown, to decide when to use what kind of interpolation:
![dec-tree](https://upload.wikimedia.org/wikipedia/commons/c/c3/Decision_tree_for_selecting_a_suitable_spatial_prediction_model.jpg)

So in your case, it could be possible that you could simply use inverse distance weighting.

Cheers,
Sebastian

**Comment by srimaljq1** [comment]
Thanks for the insights and link.

I've added in an interactive 3D scatter plot in https://colab.research.google.com/drive/1vbVhLfHt-C-_R84bxuKMMyuskegTpUMa

On that note, are there any standard tests I can perform on the data to assess if its suitable for kriging at all or which type of kriging to use? If so can I use pykrige for the assesment?
I'm thinking of something similar to performing a singularity test before trying to compute the inverse of a matrix.

**Comment by antunesleo** [comment]
In the business cases in the company I work for, we interpolate geospatial data. So, the grid we predict is always bigger than the sample grid. I didn't understand why predict a grid that I already know the all values. 
About the kriging, I know some practical stuff but I suck in theorical concepts! 

> Hi
> 
> First of all, let me warn you that I'm fairly new to kriging :-)
> 
> My intention here was to see what value the interpolation would give on the original data used to build the model, which is why I passed on x and y values..
> 
> Could you please explain or point to something which explains why
> 
> > Shouldn't the grid size in the execute method be different (bigger) than the initialization grid?
> 
> Thanks

Maybe a good test to do is have an real world geospatial data, for example a 100x100 grid that you know all the values. Then,  just use an 15x15 grid samples (kriging object creation) and run the kriging for the same 100x100 grid. If we compare the results, the predicted data  should be similar to real data. Using non real/aleatory data maybe will lead to strange results because kriging use geospatial correlation concepts, @MuellerSeb is this correct?

**Comment by srimaljq1** [comment]
Thanks for the input.

Answering myself, the negative predictions I got could be due to lack of proper parameter tuning. I've looked at the first variagram and changed parameters to get a model with a much lower nugget and more realistic predictions in the bottom half of that notebook. Perhaps I could use pykrige-cv for a more rigorous parameter tuning.

Btw that data is a subset of samples extracted from real geospatial data, just to test my understanding of using pykrig and kriging in general. :)

**Comment by antunesleo** [comment]
@srimaljq1 Should the predicted data be identical to real data in your sample? Or you expect it to be at least very similar?

**Comment by srimaljq1** [comment]
My understanding of kriging  is not sufficient to say if its should be identical, but I would atleast expect them to be similar (so not -14.0 for a value of 0.2 for e.g)

**Comment by MuellerSeb** [comment]
You changed parameters result in a non-singular kriging-matrix, which results in more accurate results.
Maybe your subset is a bit to sparse, since it show really a high nugget. The bad results are really just numerical artifacts IMO. The routines in numpy to invert the matrix are sometimes a bit erroneous.

@antunesleo : kriging is based on two-point statistics and the concept of the variogram. So yes, the spatial correlation is an essential part of kriging. As I have mentioned, when you can't estimate a proper empirical variogram to your data, you could go with inverse distance weighting.

@srimaljq1 : I hope all this could help you!

**Comment by srimaljq1** [comment]
Yes its been very helpful. Thanks!
