### ISSUE TITLE
Interpolation for time seri

### ISSUE THREAD

**Issue by hoseinsalehi** [GeoStat-Framework/PyKrige#169]
Hello 
I want to do an interpolation point for a period of 15 years using 10 stations. Is there a way to use this package?

**Comment by MuellerSeb** [comment]
Hey there,

That is depending on what you want to do. You should be a bit more specific and have a look at the documentation. And you can always contribute to the package, if you see a lack of features, since this is a community project.

Daily interpolation of data? I think so.
Spatio-temporal interpolation? No, up to now, we don't support spatio-temporal variograms.

Cheers,
Sebastian

**Comment by hoseinsalehi** [comment]
Hi @MuellerSeb, 
Thanks for your reply.
Yes, I want to do interpolation for daily precipitation data using observation stations and develop a precipitation network for a basin.
If the code can be modified to take inputs from an Excel or text file and done in a loop, I can be achieved.

I'm not a developer and I'm not even sure if my idea is right.

**Comment by MuellerSeb** [comment]
That should be easily possible without modification of PyKrige itself. To read excel files you should have a look at [pandas](https://pandas.pydata.org/).

Good luck!

Sebastian
