### ISSUE TITLE
Is PyKrige able to determine Simple kriging

### ISSUE THREAD

**Issue by jtilson** [GeoStat-Framework/PyKrige#181]
Hello Folks, PyKrige 1.5.1 is nice. Q: Can I use PyKrige to perform a simple kriging while declaring the mean to be zero?
Regards,
jeff

**Comment by jtilson** [comment]
Is already avail in GSTools

**Comment by MuellerSeb** [comment]
@jtilson you just gave the right answer ;-)

Since PyKrige will reuse the Routines of GSTools in the future, you can just use this. I also want to point out that the Gaussian Processes submodule of scikit-learn (https://scikit-learn.org/stable/modules/gaussian_process.html) is basically simple kriging.

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Also see: #152

**Comment by jtilson** [comment]
Thank you Sebastian


-------------------------------------------

Jeffrey Tilson

Senior Research Scientist

Renaissance Computing Institute

UNC Chapel Hill

(919) 445-9657

________________________________
