### ISSUE TITLE
problem with geographical coordinates and GSTools Covmodel

### ISSUE THREAD

**Issue by Mercuron** [GeoStat-Framework/PyKrige#217]
Hi all! 

1) I can't figure out how to beat the dim error. I set dim=2, but there is still error _ValueError: GSTools: model dim is not 1 or 2_.  It's probably very silly, but I can't find where it is. 

2) Why there is no predict method in the description of OK and UK methods? How then to predict results on new points?

[values.csv](https://github.com/GeoStat-Framework/PyKrige/files/7834647/values.csv)

[example_of_error.ipynb.zip](https://github.com/GeoStat-Framework/PyKrige/files/7834654/example_of_error.ipynb.zip)

**Comment by MuellerSeb** [comment]
Hi there,

sorry for the late reply. This is a compatibility issue between GSTools and PyKrige. You were using the latlon mode of the Spherical model and PyKrige doesn't check for that correctly.

I need to investigate this.

**Comment by MuellerSeb** [comment]
This only affects `OrdinaryKriging`, since the support for geographic coordinates in `UniversalKriging` was not implemented.

TODOs:
- fix `pykrige_vario` in GSTools, to return the yadrenko variogram if using latlon.
  https://github.com/GeoStat-Framework/GSTools/blob/5161e58419578beed74831e79d970a90f6975fa2/gstools/covmodel/base.py#L324
- check for `field_dim` rather than `dim` when using latlon models from GSTools. This is the root of the error since the earth is 3D, the model dim is 3, but the field itself has only 2 dimensions.
