### ISSUE TITLE
kr and ck are not imported in __init__.py

### ISSUE THREAD

**Issue by hayato-n** [GeoStat-Framework/PyKrige#270]
I installed this library and tried to use RegressionKriging. But I could not import `pykrige.rk`.

I found that in [__init__.py](https://github.com/GeoStat-Framework/PyKrige/blob/70c4e7bbcea10f42fd2290cfaa06d345adbcf444/src/pykrige/__init__.py#L43) , `rk.py` and `ck.py` are not imported and are not added to `__all__`.

I suspect that they should be added.

**Comment by MuellerSeb** [comment]
Since scikit-learn is an optional dependency, this would immediately raise an error [here](https://github.com/GeoStat-Framework/PyKrige/blob/eb86fb2ed5d373e25daf63ddc7657424bd7802b1/src/pykrige/compat.py#L89) if it is not installed.

You should use the imports shown in the documentation [here](https://geostat-framework.readthedocs.io/projects/pykrige/en/v1.7.0/examples/07_regression_kriging2d.html) and [here](https://geostat-framework.readthedocs.io/projects/pykrige/en/v1.7.0/examples/10_classification_kriging2d.html):
```python
from pykrige.rk import RegressionKriging
from pykrige.ck import ClassificationKriging
```
